apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eyfk5p7ar-python 
  janus-idp.io/tekton: eyfk5p7ar-python
  backstage.io/kubernetes-id: eyfk5p7ar-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eyfk5p7ar-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  