apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: eyfk5p7ar-python-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/eyfk5p7ar-python-gitops