apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: eyfk5p7ar-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eyfk5p7ar-python 
  name: eyfk5p7ar-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: eyfk5p7ar-python
    weight: 100 
