apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eyfk5p7ar-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eyfk5p7ar-python 
  name: eyfk5p7ar-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eyfk5p7ar-python 
